# References:
# https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    outputs:
      git_branch: ${{ steps.git_info.outputs.GIT_BRANCH }}
      git_tag: ${{ steps.git_info.outputs.GIT_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Get info on commit
        id: git_info
        run: |
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"

      - name: Build package
        run: poetry build

      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    needs: ["build"]

    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/bitbucket_pipeline_runner-${{ needs.build.outputs.GIT_TAG }}.tar.gz
            ./dist/bitbucket_pipeline_runner-${{ needs.build.outputs.GIT_TAG }}-py3-none-any.whl

  publish:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    needs: ["build"]
    environment:
      name: pypi
      url: https://pypi.org/p/bitbucket-pipeline-runner
    permissions:
      id-token: write  # Needed for publishing to PyPI with OIDC

    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
