# References:
# https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    outputs:
      git_branch: ${{ steps.git_info.outputs.GIT_BRANCH }}
      git_tag: ${{ steps.git_info.outputs.GIT_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Install Poetry
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0

      - name: Get info on commit
        id: git_info
        run: |
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"

      - name: Build package
        run: poetry build

      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    needs: ["build"]

    steps:
      - name: Retrieve build
        uses: actions/download-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ needs.build.outputs.GIT_TAG }}
          files: |
            ./dist/bitbucket_pipeline_runner-${{ needs.build.outputs.GIT_TAG }}.tar.gz
            ./dist/bitbucket_pipeline_runner-${{ needs.build.outputs.GIT_TAG }}-py3-none-any.whl

  publish:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    needs: ["build"]
    environment:
      name: pypi
      url: https://pypi.org/p/bitbucket-pipeline-runner
    permissions:
      id-token: write  # Needed for publishing to PyPI with OIDC

    steps:
      - name: Retrieve build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
