# References:
# https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Get info on commit
        id: git_info
        run: |
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"

      - name: Build package
        run: |
          poetry build

      - name: Upload release archive
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_name: bitbucket_pipeline_runner-${{ steps.git_info.outputs.GIT_TAG }}.tar.gz
          asset_path: ./dist/bitbucket_pipeline_runner-${{ steps.git_info.outputs.GIT_TAG }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload wheel
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_name: bitbucket_pipeline_runner-${{ steps.git_info.outputs.GIT_TAG }}-py3-none-any.whl
          asset_path: ./dist/bitbucket_pipeline_runner-${{ steps.git_info.outputs.GIT_TAG }}-py3-none-any.whl
          asset_content_type: application/zip

      - name: Upload package to PyPI
        run: |
          poetry publish --username __token__ --password "${{ secrets.PYPI_TOKEN }}"
